language: en

pipeline:
  - name: VietnameseTokenizer
  #  - name: entity_extractor.EntityExtractor
  #  - name: EntitySynonymMapper
  - name: LanguageModelFeaturizer
    # Name of the language model to use
    model_name: "roberta"
    # Pre-Trained weights to be loaded
    model_weights: "vinai/phobert-base"
    cache_dir: null
  - name: RegexFeaturizer
  - name: RegexEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 150

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
